version: '3.1'
services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
        networks:
          - bridge
    store_service:
        image: store_service
        restart: always
        container_name: store_service
        expose: 
          - 8081
        ports:
          - 8081:8080
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
        networks:
          - bridge
        depends_on:
          - mongo
    gateway:
        container_name: gateway_service
        image: gateway_service
        restart: always
        ports:
          - 8080:8080
        networks:
          - bridge
        depends_on:
          - store_service
          - atlas
          - katana
    atlas:
        container_name: atlas
        image: 14jthaxton/atlas:1.0
        environment: 
          - POSTGRESQL_URL="postgres://root:example@localhost:5432/job_db?sslmode=disable"
        command: migrate -database ${POSTGRESQL_URL} -path db/migrations up
        ports:
          - "8082:8080"
        depends_on:
          - postgres
        links:
          - postgres
        networks:
          - bridge
    postgres:
        container_name: job_db
        image: postgres
        environment:
          POSTGRES_USER: 'root'
          POSTGRES_PASSWORD: 'example'
          POSTGRES_DB: 'job_db'
        ports:
          - "5432:5432"
        networks:
          - bridge
    katana:
      image: 14jthaxton/katana:1.0
      container_name: katana
      ports:
          - "8083:8080"
      networks:
          - bridge
networks:
  bridge:
    driver: bridge